on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://npm.pkg.github.com
        scope: '@definitelytyped'
    - name: lint
      run: npm run lint
    - name: test
      run: npm test
    - name: version
      run: lerna version ${{ GITHUB_REF }}
    - name: publish
      run: lerna publish from-git --yes
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
