on:
  release:
    types: [created]
jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
        registry-url: https://registry.npmjs.org
    - name: configure git
      run: |
        git config user.email "typescriptbot@microsoft.com"
        git config user.name "TypeScript Bot"
    - name: install
      run: npm ci
    - name: lint
      run: npm run lint
    - name: test
      run: npm test
    - name: version
      run: |
        ref=${{ github.ref }} # refs/tags/v0.0.1
        tag=${ref:11} # 0.0.1
        npx lerna version $tag --yes --tag-version-prefix=''
    - name: publish to npm
      run: npx lerna publish from-git --yes --tag-version-prefix='' --no-verify-access
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
